-- Create Media Types table
CREATE TABLE media_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, -- 'Anime', 'Manga', 'Game', 'Movie'
  icon TEXT, -- Icon identifier for UI
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert initial media types
INSERT INTO media_types (name, icon) VALUES 
('Anime', 'play-circle'),
('Manga', 'book-open'),
('Game', 'gamepad-2'),
('Movie', 'clapperboard');

-- Create Media Items table (Replacement for anime table)
CREATE TABLE media_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_type_id BIGINT REFERENCES media_types(id) NOT NULL,
  title TEXT NOT NULL,
  cover_image TEXT,
  banner_image TEXT,
  external_id INTEGER, -- MAL ID, IGDB ID, TMDB ID, etc.
  external_api TEXT, -- 'mal', 'igdb', 'tmdb', etc.
  status_id BIGINT REFERENCES categories(id),
  score INTEGER DEFAULT 0 NOT NULL,
  genres TEXT[],
  release_year INTEGER,
  trailer_url TEXT,
  notes TEXT,
  start_date TIMESTAMP WITH TIME ZONE[],
  end_date TIMESTAMP WITH TIME ZONE[],
  source_links JSONB DEFAULT '[]'::jsonb, -- Watch/read/play source links
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  temp_orig_id BIGINT -- Temporary column for migration mapping
);

-- Anime-specific metadata
CREATE TABLE anime_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  studios TEXT[],
  mal_id INTEGER,
  episodes_watched INTEGER DEFAULT 0 NOT NULL,
  episodes_total INTEGER DEFAULT 0 NOT NULL,
  publication_status TEXT -- 'Publishing', 'Finished', 'Hiatus'
);

-- Manga-specific metadata
CREATE TABLE manga_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  mal_id INTEGER,
  authors TEXT[],
  publishers TEXT[],
  chapters_total INTEGER DEFAULT 0 NOT NULL,
  chapters_read INTEGER DEFAULT 0 NOT NULL,
  publication_status TEXT -- 'Publishing', 'Finished', 'Hiatus'
);

-- Game-specific metadata
CREATE TABLE game_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  igdb_id INTEGER,
  developers TEXT[],
  publishers TEXT[],
  platforms TEXT[], -- 'PC', 'PS5', 'Xbox', 'Switch', etc.
  hours_played INTEGER DEFAULT 0 NOT NULL,
  hltb_hours INTEGER DEFAULT 0 NOT NULL -- How Long To Beat hours
);

-- Movie-specific metadata
CREATE TABLE movie_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  tmdb_id INTEGER,
  directors TEXT[],
  "cast" TEXT[],
  studios TEXT[],
  runtime_minutes INTEGER
);

-- Enable Row Level Security (RLS)
ALTER TABLE media_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE anime_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE manga_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_metadata ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public access" ON media_types FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON media_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON anime_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON manga_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON game_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON movie_metadata FOR ALL USING (true) WITH CHECK (true);

-- Migration: Copy existing anime data to media_items
INSERT INTO media_items (
  title, cover_image, external_id, 
  status_id, score, genres, release_year, notes, 
  source_links, is_deleted, created_at, updated_at, media_type_id, external_api,
  temp_orig_id
)
SELECT 
  title, cover_image, mal_id, 
  status_id, score, genres, release_year, notes, 
  watch_links, is_deleted, created_at, updated_at, 1, 'mal',
  id
FROM anime;

-- Migration: Copy anime-specific metadata
INSERT INTO anime_metadata (media_item_id, studios, mal_id, episodes_watched, episodes_total)
SELECT mi.id, a.studios, a.mal_id, a.episodes_watched, a.total_episodes
FROM media_items mi
JOIN anime a ON mi.temp_orig_id = a.id
WHERE mi.media_type_id = 1;

-- Add media_item_ids to lists table
ALTER TABLE lists ADD COLUMN media_item_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[];

-- Create a temporary mapping table to help with list migration
CREATE TEMP TABLE id_mapping (
  old_id BIGINT,
  new_id BIGINT
);

INSERT INTO id_mapping (old_id, new_id)
SELECT temp_orig_id, id
FROM media_items
WHERE temp_orig_id IS NOT NULL;

-- Function to migrate array of IDs
CREATE OR REPLACE FUNCTION migrate_list_ids(old_ids BIGINT[])
RETURNS BIGINT[] AS $$
DECLARE
  new_ids BIGINT[] := ARRAY[]::BIGINT[];
  id_to_map BIGINT;
  mapped_id BIGINT;
BEGIN
  FOREACH id_to_map IN ARRAY old_ids LOOP
    SELECT m.new_id INTO mapped_id FROM id_mapping m WHERE m.old_id = id_to_map;
    IF mapped_id IS NOT NULL THEN
      new_ids := array_append(new_ids, mapped_id);
    END IF;
  END LOOP;
  RETURN new_ids;
END;
$$ LANGUAGE plpgsql;

-- Update lists
UPDATE lists SET media_item_ids = migrate_list_ids(anime_ids);

-- Cleanup
DROP FUNCTION migrate_list_ids(BIGINT[]);
DROP TABLE id_mapping;
ALTER TABLE media_items DROP COLUMN temp_orig_id;
