-- Migration: Create Media Reviews table and migrate data
-- This script fixes the foreign key error by creating a generic media_reviews table linked to media_items

-- 1. Create Media Reviews table
CREATE TABLE IF NOT EXISTS media_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_item_id BIGINT REFERENCES media_items(id) ON DELETE CASCADE,
  review_text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Migrate data from anime_reviews if it exists and hasn't been migrated yet
-- We use media_items.external_id to match mal_id from anime_reviews if available, 
-- or we assume the IDs might be different and need mapping.
-- If you just migrated to media_items, you likely used mapped IDs.

DO $$ 
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'anime_reviews') THEN
    -- Only insert if media_reviews is empty (prevent double migration)
    IF (SELECT COUNT(*) FROM media_reviews) = 0 THEN
      -- This assumes media_items was populated from anime table and we can find the link.
      -- If you used temp_orig_id during migration, use it.
      -- If not, we try to match by title (risky) or skip.
      
      -- Let's check if temp_orig_id still exists (some migrations drop it at the end)
      IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'media_items' AND column_name = 'temp_orig_id') THEN
        INSERT INTO media_reviews (media_item_id, review_text, created_at, updated_at)
        SELECT mi.id, ar.review_text, ar.created_at, ar.updated_at
        FROM anime_reviews ar
        JOIN media_items mi ON mi.temp_orig_id = ar.anime_id;
      ELSE
        -- Fallback: try to match by external_id (mal_id)
        INSERT INTO media_reviews (media_item_id, review_text, created_at, updated_at)
        SELECT mi.id, ar.review_text, ar.created_at, ar.updated_at
        FROM anime_reviews ar
        JOIN anime a ON ar.anime_id = a.id
        JOIN media_items mi ON mi.external_id = a.mal_id AND mi.media_type_id = 1;
      END IF;
    END IF;
  END IF;
END $$;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE media_reviews ENABLE ROW LEVEL SECURITY;

-- 4. Create policy for public access
DROP POLICY IF EXISTS "Allow public access" ON media_reviews;
CREATE POLICY "Allow public access" ON media_reviews FOR ALL USING (true) WITH CHECK (true);

-- 5. (Optional) Drop old table after verification
-- DROP TABLE anime_reviews;
