-- Create Media Types table
CREATE TABLE media_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, -- 'Anime', 'Manga', 'Game', 'Movie'
  icon TEXT, -- Icon identifier for UI
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert initial media types
INSERT INTO media_types (name, icon) VALUES 
('Anime', 'play-circle'),
('Manga', 'book-open'),
('Game', 'gamepad-2'),
('Movie', 'clapperboard');

-- Create Media Items table (Replacement for anime table)
CREATE TABLE media_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_type_id BIGINT REFERENCES media_types(id) NOT NULL,
  title TEXT NOT NULL,
  cover_image TEXT,
  banner_image TEXT,
  external_id INTEGER, -- MAL ID, IGDB ID, TMDB ID, etc.
  external_api TEXT, -- 'mal', 'igdb', 'tmdb', etc.
  progress_current INTEGER DEFAULT 0 NOT NULL, -- Episodes watched, chapters read, hours played, etc.
  progress_total INTEGER DEFAULT 0 NOT NULL,
  status_id BIGINT REFERENCES categories(id),
  score INTEGER DEFAULT 0 NOT NULL,
  genres TEXT[],
  release_year INTEGER,
  trailer_url TEXT,
  notes TEXT,
  activity_dates TIMESTAMP WITH TIME ZONE[], -- Watch/read/play dates
  source_links JSONB DEFAULT '[]'::jsonb, -- Watch/read/play source links
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Anime-specific metadata
CREATE TABLE anime_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  studios TEXT[],
  mal_id INTEGER
);

-- Manga-specific metadata
CREATE TABLE manga_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  authors TEXT[],
  publishers TEXT[],
  mal_id INTEGER,
  publication_status TEXT -- 'Publishing', 'Finished', 'Hiatus'
);

-- Game-specific metadata
CREATE TABLE game_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  developers TEXT[],
  publishers TEXT[],
  platforms TEXT[], -- 'PC', 'PS5', 'Xbox', 'Switch', etc.
  igdb_id INTEGER,
  playtime_hours DECIMAL(10, 2)
);

-- Movie-specific metadata
CREATE TABLE movie_metadata (
  media_item_id BIGINT REFERENCES media_items(id) PRIMARY KEY,
  directors TEXT[],
  cast TEXT[],
  studios TEXT[],
  tmdb_id INTEGER,
  runtime_minutes INTEGER
);

-- Enable Row Level Security (RLS)
ALTER TABLE media_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE anime_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE manga_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_metadata ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public access" ON media_types FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON media_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON anime_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON manga_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON game_metadata FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON movie_metadata FOR ALL USING (true) WITH CHECK (true);

-- Migration: Copy existing anime data to media_items
INSERT INTO media_items (
  title, cover_image, external_id, progress_current, progress_total, 
  status_id, score, genres, release_year, notes, activity_dates, 
  source_links, is_deleted, created_at, updated_at, media_type_id, external_api
)
SELECT 
  title, cover_image, mal_id, episodes_watched, total_episodes, 
  status_id, score, genres, release_year, notes, watch_dates, 
  watch_links, is_deleted, created_at, updated_at, 1, 'mal'
FROM anime;

-- Migration: Copy anime-specific metadata
INSERT INTO anime_metadata (media_item_id, studios, mal_id)
SELECT mi.id, a.studios, a.mal_id
FROM media_items mi
JOIN anime a ON mi.title = a.title AND mi.created_at = a.created_at
WHERE mi.media_type_id = 1;

-- Add media_item_ids to lists table
ALTER TABLE lists ADD COLUMN media_item_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[];

-- Create a temporary mapping table to help with list migration
CREATE TEMP TABLE id_mapping (
  old_id BIGINT,
  new_id BIGINT
);

INSERT INTO id_mapping (old_id, new_id)
SELECT a.id, mi.id
FROM anime a
JOIN media_items mi ON mi.title = a.title AND mi.created_at = a.created_at
WHERE mi.media_type_id = 1;

-- Function to migrate array of IDs
CREATE OR REPLACE FUNCTION migrate_list_ids(old_ids BIGINT[])
RETURNS BIGINT[] AS $$
DECLARE
  new_ids BIGINT[] := ARRAY[]::BIGINT[];
  old_id BIGINT;
  new_id BIGINT;
BEGIN
  FOREACH old_id IN ARRAY old_ids LOOP
    SELECT m.new_id INTO new_id FROM id_mapping m WHERE m.old_id = old_id;
    IF new_id IS NOT NULL THEN
      new_ids := array_append(new_ids, new_id);
    END IF;
  END LOOP;
  RETURN new_ids;
END;
$$ LANGUAGE plpgsql;

-- Update lists
UPDATE lists SET media_item_ids = migrate_list_ids(anime_ids);

-- Cleanup
DROP FUNCTION migrate_list_ids(BIGINT[]);
DROP TABLE id_mapping;
