-- Migration to create folders and lists tables
-- Run this in your Supabase SQL Editor

-- Create Folders table
CREATE TABLE IF NOT EXISTS folders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  "order" INTEGER DEFAULT 0 NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Lists table
CREATE TABLE IF NOT EXISTS lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_id BIGINT REFERENCES folders(id),
  name TEXT NOT NULL,
  description TEXT,
  anime_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE lists ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow all for now, to match existing schema)
CREATE POLICY "Allow public access" ON folders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON lists FOR ALL USING (true) WITH CHECK (true);
