-- Create Categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  "order" INTEGER NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Watch Sources table
CREATE TABLE watch_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  base_url TEXT,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Anime table
CREATE TABLE anime (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  cover_image TEXT,
  mal_id INTEGER,
  episodes_watched INTEGER DEFAULT 0 NOT NULL,
  total_episodes INTEGER DEFAULT 0 NOT NULL,
  status_id BIGINT REFERENCES categories(id),
  score INTEGER DEFAULT 0 NOT NULL,
  genres TEXT[],
  studios TEXT[],
  release_year INTEGER,
  notes TEXT,
  watch_dates TIMESTAMP WITH TIME ZONE[],
  watch_links JSONB DEFAULT '[]'::jsonb,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE watch_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE anime ENABLE ROW LEVEL SECURITY;

-- Create policies (Example: Allow all for now, you should refine this for Auth)
CREATE POLICY "Allow public access" ON categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON watch_sources FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON anime FOR ALL USING (true) WITH CHECK (true);

-- Create Folders table
CREATE TABLE folders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  "order" INTEGER DEFAULT 0 NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Lists table
CREATE TABLE lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_id BIGINT REFERENCES folders(id),
  name TEXT NOT NULL,
  description TEXT,
  anime_ids BIGINT[] DEFAULT ARRAY[]::BIGINT[],
  is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) for new tables
ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE lists ENABLE ROW LEVEL SECURITY;

-- Create policies for new tables
CREATE POLICY "Allow public access" ON folders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public access" ON lists FOR ALL USING (true) WITH CHECK (true);
